using System.Collections.Generic;

namespace ZestDrop;

// English for every Chinese source string. Keys must match the L.T / L.F arguments exactly;
// ProgressChecks fails if any key used in the code is missing here.
internal static partial class L
{
    private static readonly Dictionary<string, string> En = new()
    {
        // Punctuation appended to messages
        ["。"] = ".",

        // Progress
        ["已暂停"] = "Paused",
        ["等待处理"] = "Waiting",
        ["处理完成"] = "Done",
        ["处理未完成"] = "Not completed",
        ["处理已停止"] = "Stopped",
        ["已用 {0} 分 {1} 秒"] = "Elapsed {0} min {1} s",
        ["已用 {0} 秒"] = "Elapsed {0} s",
        ["前面的任务完成后开始"] = "Starts when a running job finishes",
        ["已处理 {0} / {1} 项  ·  {2}"] = "{0} of {1} done  ·  {2}",
        ["正在转换格式"] = "Converting",
        ["正在处理文件"] = "Processing",
        [" 等 {0} 项"] = " and {1} more", // {0} = all files, {1} = the others
        ["暂停"] = "Pause",
        ["继续"] = "Resume",
        ["取消"] = "Cancel",
        ["隐藏"] = "Hide",
        ["暂停此任务，稍后可继续"] = "Pause this job; resume it any time",
        ["从暂停处继续处理"] = "Continue from where it paused",
        ["停止此任务并清理未完成的文件"] = "Stop this job and remove its unfinished files",
        ["隐藏这张卡片，任务继续在后台运行；可从托盘菜单重新显示"] = "Hide this card. The job keeps running; show it again from the tray menu",
        ["ZestDrop 处理进度"] = "ZestDrop progress",
        ["收起"] = "Collapse",
        ["展开"] = "Expand",
        ["把卡片叠成一摞，只显示最新的任务"] = "Pile the cards up and show only the newest job",
        ["从上到下列出所有任务"] = "List every job from top to bottom",
        ["显示全部"] = "Show all",
        ["重新显示被隐藏的卡片"] = "Show hidden cards again",
        ["全部隐藏"] = "Hide all",
        ["隐藏进度，任务继续在后台运行；可从托盘菜单重新显示"] = "Hide progress. Jobs keep running; show them again from the tray menu",
        ["{0} 个任务"] = "{0} jobs",
        ["进行中 {0}"] = "running {0}",
        ["已暂停 {0}"] = "paused {0}",
        ["等待 {0}"] = "waiting {0}",
        ["已隐藏 {0}"] = "hidden {0}",

        // Engine and process errors
        ["无法启动本地处理引擎"] = "Could not start the local processing engine",
        ["本地引擎未完成处理"] = "The local engine did not finish",
        ["无法启动本地处理进程"] = "Could not start the local processing process",
        ["处理引擎未正常完成"] = "The processing engine did not finish normally",
        ["无法暂停处理进程"] = "Could not pause the processing job",
        ["无法暂停"] = "Could not pause",

        // Tray and notifications
        ["ZestDrop · 拖文件 + Shift 转换 / Ctrl+Shift 工具"] = "ZestDrop · Drag + Shift to convert / Ctrl+Shift for tools",
        ["使用方式：拖文件 + Shift / Ctrl+Shift"] = "How to use: drag a file + Shift / Ctrl+Shift",
        ["显示处理进度"] = "Show progress",
        ["暂停全部任务"] = "Pause all jobs",
        ["继续全部任务"] = "Resume all jobs",
        ["取消全部任务"] = "Cancel all jobs",
        ["最近输出所在文件夹"] = "Open latest output folder",
        ["第三方组件许可"] = "Third-party notices",
        ["退出 ZestDrop"] = "Quit ZestDrop",
        ["语言"] = "Language",
        ["已切换为简体中文"] = "Switched to English",
        ["ZestDrop 已运行"] = "ZestDrop is running",
        ["拖文件 + Shift：转换；Ctrl+Shift：工具。拖拽时也可按 F8/F9。"] = "Drag a file + Shift: convert. Ctrl+Shift: tools. F8/F9 also work while dragging.",
        ["任务队列已满"] = "The job queue is full",
        ["请等正在处理的文件完成后重试。"] = "Please try again when the current files have finished.",
        ["新文件已保存"] = "New file saved",
        ["新文件已保存到原文件夹。"] = "New files were saved next to the originals.",
        ["成功 {0} 项 · 失败 {1} 项"] = "{0} succeeded · {1} failed",
        ["完成 {0} 项"] = "{0} done",
        [" · 失败 {0} 项"] = " · {0} failed",
        ["此任务已取消。"] = "This job was cancelled.",
        ["此任务已取消，未完成的临时文件已清理。"] = "This job was cancelled and its unfinished files were removed.",
        ["转换未完成"] = "Conversion not completed",

        // Welcome window
        ["欢迎使用 ZestDrop"] = "Welcome to ZestDrop",
        ["拖动，松手，转换。"] = "Drag. Drop. Convert.",
        ["拖动文件"] = "Drag files",
        ["在桌面或资源管理器中选中一个或多个文件，像移动文件一样开始拖动。"] = "Select one or more files on the desktop or in File Explorer and start dragging them, as if you were moving them.",
        ["按下 Shift"] = "Press Shift",
        ["拖动时按 Shift 打开格式菜单，按 Ctrl+Shift 打开工具菜单。菜单出现后可以松开按键。"] = "While dragging, press Shift for the format menu or Ctrl+Shift for the tools menu. Once the menu appears you can let go of the keys.",
        ["在选项上松手"] = "Release on an option",
        ["新文件会保存在原文件旁边，原文件不会被改动。"] = "The new file is saved next to the original, which is never changed.",
        ["ZestDrop 在通知区域（任务栏右侧时钟旁）运行，没有主窗口。右键托盘图标可暂停或取消任务、切换语言或退出。看不到图标？点击任务栏上的 ^ 箭头。"] = "ZestDrop runs in the notification area (next to the clock) and has no main window. Right-click its icon to pause or cancel jobs, change the language or quit. Can't see the icon? Click the ^ arrow on the taskbar.",
        ["所有处理都在本机完成，不上传任何文件，也不联网。"] = "Everything is processed on this PC. Nothing is uploaded, and ZestDrop never connects to the internet.",
        ["启动时不再显示此窗口"] = "Don't show this window when ZestDrop starts",
        ["知道了"] = "Got it",

        // Debug previews
        ["ZestDrop 播放器检查"] = "ZestDrop player check",
        ["假期视频.mp4"] = "holiday-video.mp4",
        ["照片 1.heic"] = "photo 1.heic",
        ["照片 2.heic"] = "photo 2.heic",
        ["照片 3.heic"] = "photo 3.heic",

        // Floating wheel
        ["ZestDrop 浮动菜单"] = "ZestDrop menu",
        ["拖入文件"] = "Drop files",
        ["Shift 格式 · Ctrl+Shift 工具"] = "Shift formats · Ctrl+Shift tools",
        ["工具随类型显示"] = "Tools depend on the file type",
        ["格式随类型显示"] = "Formats depend on the file type",
        ["仅支持打包"] = "Packing only",
        ["1 个文件"] = "1 file",
        ["{0} 个文件"] = "{0} files",
        ["无可用操作"] = "No actions",
        ["暂不支持格式转换"] = "No conversions for this type",
        ["选操作后松手"] = "Release on an option",
        ["Esc 取消"] = "Esc to cancel",

        // Operations (wheel petals and tool window titles)
        ["打包 "] = "Pack ",
        ["未知工具 "] = "Unknown tool ",
        ["选页导出 PDF"] = "Export pages",
        ["合并为 PDF"] = "Merge into PDF",
        ["压缩"] = "Compress",
        ["元数据"] = "Metadata",
        ["编辑图片"] = "Edit image",
        ["添加背景"] = "Add background",
        ["裁剪"] = "Crop",
        ["图片打码"] = "Redact",
        ["创建 PDF"] = "Make PDF",
        ["拼图"] = "Collage",
        ["移除音频"] = "Remove audio",
        ["裁剪时段"] = "Trim",
        ["裁剪画面"] = "Crop frame",
        ["调整速度"] = "Speed",
        ["拼接视频"] = "Join videos",
        ["保存帧"] = "Save frames",
        ["分段"] = "Split",
        ["视频打码"] = "Redact",
        ["标准化响度"] = "Normalize loudness",
        ["音频可视化"] = "Waveform video",
        ["裁剪音频"] = "Trim audio",
        ["声道"] = "Channels",
        ["消音蜂鸣"] = "Bleep",
        ["拆分 PDF"] = "Split PDF",
        ["合并 PDF"] = "Merge PDFs",
        ["管理页面"] = "Pages",
        ["解包"] = "Extract",

        // Tool fields
        ["左侧 x（像素）"] = "Left x (px)",
        ["顶部 y（像素）"] = "Top y (px)",
        ["宽度（像素）"] = "Width (px)",
        ["高度（像素）"] = "Height (px)",
        ["开始（秒 / 时:分:秒）"] = "Start (seconds or h:m:s)",
        ["结束（0 表示结尾）"] = "End (0 = end of file)",
        ["比例"] = "Aspect ratio",
        ["宽比例"] = "Ratio width",
        ["高比例"] = "Ratio height",
        ["导出页码（逗号分隔，留空全部）"] = "Pages to export (comma-separated, blank for all)",
        ["比特率（kbps）"] = "Bitrate (kbps)",
        ["目标大小（KB，0 不限制）"] = "Target size (KB, 0 = no limit)",
        ["CRF（越高压缩越强）"] = "CRF (higher = smaller file)",
        ["质量（1–100）"] = "Quality (1–100)",
        ["最长边（像素）"] = "Longest side (px)",
        ["移除全部元数据"] = "Remove all metadata",
        ["搜索元数据字段"] = "Search metadata fields",
        ["元数据字段（关闭全部移除后可修改）"] = "Metadata fields (editable when “Remove all” is off)",
        ["曝光（EV）"] = "Exposure (EV)",
        ["对比度（1 原始）"] = "Contrast (1 = original)",
        ["饱和度（1 原始）"] = "Saturation (1 = original)",
        ["色温（-100 到 100）"] = "Temperature (-100 to 100)",
        ["阴影（-100 到 100）"] = "Shadows (-100 to 100)",
        ["高光（-100 到 100）"] = "Highlights (-100 to 100)",
        ["清晰度（0–100）"] = "Clarity (0–100)",
        ["去雾（0–100）"] = "Dehaze (0–100)",
        ["降噪（0–30）"] = "Noise reduction (0–30)",
        ["颗粒（0–100）"] = "Grain (0–100)",
        ["标注（JSON，可选）"] = "Annotations (JSON, optional)",
        ["画布宽度"] = "Canvas width",
        ["画布高度"] = "Canvas height",
        ["留白"] = "Padding",
        ["圆角"] = "Corner radius",
        ["阴影"] = "Shadow",
        ["背景色"] = "Background colour",
        ["渐变结束色"] = "Gradient end colour",
        ["背景图片"] = "Background image",
        ["背景模糊"] = "Background blur",
        ["打码方式"] = "Redaction style",
        ["马赛克颗粒（像素）"] = "Pixel block size (px)",
        ["覆盖颜色"] = "Fill colour",
        ["多个区域"] = "Multiple regions",
        ["布局"] = "Layout",
        ["网格列数（0 自动）"] = "Grid columns (0 = auto)",
        ["间距"] = "Gap",
        ["速度（0.125–8）"] = "Speed (0.125–8)",
        ["时间（秒）"] = "Time (seconds)",
        ["相对帧数"] = "Frame offset",
        ["多个时间点（秒，逗号分隔）"] = "Several times (seconds, comma-separated)",
        ["均分段数"] = "Number of equal parts",
        ["自定义分割点（秒，逗号分隔）"] = "Custom split points (seconds, comma-separated)",
        ["多个区域和各自时段"] = "Regions and their time ranges",
        ["目标响度（LUFS）"] = "Target loudness (LUFS)",
        ["响度范围（LRA）"] = "Loudness range (LRA)",
        ["真峰值（dBTP）"] = "True peak (dBTP)",
        ["画面比例"] = "Aspect ratio",
        ["静态背景图（留空为波形）"] = "Still background image (blank = waveform)",
        ["去掉开头和结尾静音"] = "Remove silence at the start and end",
        ["输出声道"] = "Output channels",
        ["左侧音量（1 原始）"] = "Left volume (1 = original)",
        ["右侧音量（1 原始）"] = "Right volume (1 = original)",
        ["多个时段"] = "Multiple ranges",
        ["每份页数"] = "Pages per file",
        ["PDF 密码（如需要）"] = "PDF password (if needed)",
        ["页码顺序（可重复或省略）"] = "Page order (pages may repeat or be left out)",
        ["全部旋转角度（0/90/180/270）"] = "Rotate all pages (0/90/180/270)",
        ["逐页旋转，如 {\"1\":90}"] = "Per-page rotation, e.g. {\"1\":90}",

        // Validation
        ["自定义比例的宽、高都需要大于 0，例如 3 : 2 或 2.35 : 1。"] = "Both sides of a custom ratio must be greater than 0, e.g. 3 : 2 or 2.35 : 1.",
        ["时间格式应为秒数或 时:分:秒。"] = "Times must be seconds or h:m:s.",
        ["时间中的分、秒需小于 60。"] = "Minutes and seconds must be less than 60.",
        ["{0}需在 {1}–{2} 范围内"] = "{0} must be between {1} and {2}",
        ["，并填写整数。"] = ", as a whole number.",
        ["需要有效数字。"] = " needs a valid number.",
        ["需要数字"] = " needs a number",
        ["的格式有误，请检查高级参数。"] = " is not valid. Please check the advanced settings.",
        ["裁剪比例的宽、高必须大于 0。"] = "Both sides of the crop ratio must be greater than 0.",
        ["旋转角度只能是 0、90、180 或 270。"] = "Rotation must be 0, 90, 180 or 270.",
        ["画布最多支持 4000 万像素。"] = "The canvas can be at most 40 megapixels.",
        ["留白必须小于画布短边的一半。"] = "Padding must be less than half the canvas's shorter side.",
        ["请先拖动选择有效区域。"] = "Drag on the preview to select an area first.",
        ["选区超出原始画面，请缩小或重新选择。"] = "The selection goes beyond the original image. Make it smaller or select again.",
        ["结束时间必须晚于开始时间，且在文件时长内。"] = "The end must be after the start and within the file's length.",
        ["时间点需在文件时长内。"] = "Times must be within the file's length.",
        ["页码需为 1{0} 的整数，以逗号分隔。"] = "Pages must be whole numbers from 1{0}, separated by commas.",

        // Media player
        ["点击定位；拖动橙色节点设置开始和结束"] = "Click to seek; drag the orange handles to set the start and end",
        ["播放进度与裁剪范围"] = "Playback position and trim range",
        ["开始 "] = "Start ",
        ["结束 "] = "End ",
        ["拖动开始节点"] = "Drag the start handle",
        ["拖动结束节点"] = "Drag the end handle",
        ["播放 / 暂停"] = "Play / pause",
        ["静音 / 取消静音"] = "Mute / unmute",
        ["原文件"] = "Original",
        ["处理效果"] = "Result",
        ["原文件 ▾"] = "Original ▾",
        ["处理效果 ▾"] = "Result ▾",
        ["播放音量"] = "Volume",
        ["当前效果片段已播放完，可拖动进度条预览其他位置。"] = "This preview clip has finished. Drag the seek bar to preview another part.",
        ["播放失败："] = "Playback failed: ",
        ["播放准备失败："] = "Could not prepare playback: ",
        ["效果播放为当前位置最多 30 秒；保存会处理完整文件或所选时段。"] = "The result preview plays up to 30 s from the current position; saving processes the whole file or selected range.",
        ["可播放完整原文件；拖动进度条定位。"] = "The whole original can be played; drag the seek bar to move around.",
        ["原文件播放 · 可定位完整文件"] = "Playing the original · the whole file can be sought",
        ["原文件兼容播放 · 可定位完整文件"] = "Playing a compatible copy of the original · the whole file can be sought",
        ["效果片段：{0}–{1} · 保存处理完整选择"] = "Preview clip: {0}–{1} · saving processes the full selection",

        // Metadata editor
        ["所属"] = "Scope",
        ["字段"] = "Field",
        ["值"] = "Value",
        ["文件"] = "File",
        ["轨道 "] = "Track ",
        ["章节 "] = "Chapter ",

        // Office
        ["此转换需要已安装的 Microsoft {0}"] = "This conversion needs Microsoft {0} installed",
        ["该 Office 文件被加密或内容损坏，请先在 Office 中确认可正常打开并另存为未加密副本"] = "This Office file is encrypted or damaged. Open it in Office first and save an unencrypted copy",
        ["无法启动 Office 转换引擎"] = "Could not start Office for the conversion",
        ["不支持的幻灯片输出格式"] = "Unsupported presentation output format",
        ["不支持的 Word 输出格式"] = "Unsupported Word output format",
        ["不支持的工作簿输出格式"] = "Unsupported workbook output format",
        ["{0} 转换失败：{1}"] = "{0} conversion failed: {1}",
        ["Office 没有生成有效的输出文件"] = "Office did not produce a valid output file",
        ["第 {0} 页"] = "Page {0}",

        // Tool window
        ["最小化"] = "Minimize",
        ["关闭"] = "Close",
        ["ZestDrop  /  工具"] = "ZestDrop  /  Tools",
        ["处理中。请先点击取消，等待任务停止后关闭窗口。"] = "Still processing. Click Cancel and wait for the job to stop before closing the window.",
        ["已选 1 个文件"] = "1 file selected",
        ["已选 {0} 个文件"] = "{0} files selected",
        ["效果预览"] = "Preview",
        ["源文件预览"] = "Source preview",
        ["查看效果"] = "Show result",
        ["查看原始"] = "Show original",
        ["正在查看原始画面。"] = "Showing the original.",
        ["播放位置（秒）"] = "Position (seconds)",
        ["上一帧"] = "Previous frame",
        ["下一帧"] = "Next frame",
        ["设为开始"] = "Set start",
        ["设为结束"] = "Set end",
        ["只裁剪画面；保留完整时长和原有音轨。"] = "Crops the picture only; the full length and audio are kept.",
        ["在预览上拖动选择裁剪范围。"] = "Drag on the preview to choose the crop area.",
        ["在预览上拖动选区，可添加多个打码区域。"] = "Drag on the preview to add areas to redact. You can add several.",
        ["重置裁剪"] = "Reset crop",
        ["清空覆盖区域"] = "Clear areas",
        ["覆盖区域已清空。请拖动添加新区域。"] = "Areas cleared. Drag on the preview to add new ones.",
        ["移除选中区域"] = "Remove selected area",
        ["在波形上拖动选择时段；可添加多个蜂鸣范围。"] = "Drag on the waveform to choose a range. You can add several bleep ranges.",
        ["清空蜂鸣范围"] = "Clear ranges",
        ["蜂鸣时段已清空。"] = "Bleep ranges cleared.",
        ["移除选中时段"] = "Remove selected range",
        ["分析原始与处理后响度"] = "Measure loudness before and after",
        ["正在分析响度"] = "Measuring loudness",
        ["分析响度…"] = "Measuring loudness…",
        ["原始 {0} LUFS · 处理后 {1} LUFS"] = "Original {0} LUFS · result {1} LUFS",
        ["分析："] = "Analysis: ",
        ["上移"] = "Move up",
        ["下移"] = "Move down",
        ["移出选择"] = "Remove",
        ["复制页"] = "Duplicate page",
        ["处理参数"] = "Settings",
        ["启用"] = "On",
        ["选择图片…"] = "Choose image…",
        ["图片|*.jpg;*.jpeg;*.png;*.webp;*.bmp;*.heic;*.avif|所有文件|*.*"] = "Images|*.jpg;*.jpeg;*.png;*.webp;*.bmp;*.heic;*.avif|All files|*.*",
        ["自定义比例（宽 : 高）"] = "Custom ratio (width : height)",
        ["高级参数（可选）"] = "Advanced settings (optional)",
        ["在左侧调整文件顺序，然后保存。"] = "Arrange the files on the left, then save.",
        ["此操作无需参数。预览确认后保存新文件。"] = "No settings needed. Check the preview, then save a new file.",
        ["读取文件信息…"] = "Reading file information…",
        ["正在读取文件"] = "Reading file",
        ["打开输出位置"] = "Show in folder",
        ["取消处理"] = "Cancel",
        ["正在停止处理…"] = "Stopping…",
        ["保存新文件"] = "Save new file",
        ["纯色遮盖"] = "Solid fill",
        ["模糊"] = "Blur",
        ["马赛克"] = "Pixelate",
        ["自由"] = "Free",
        ["自定义"] = "Custom",
        ["网格"] = "Grid",
        ["一行"] = "Row",
        ["一列"] = "Column",
        ["主图布局"] = "Featured",
        ["横向"] = "Landscape",
        ["纵向"] = "Portrait",
        ["正方形"] = "Square",
        ["单声道"] = "Mono",
        ["双声道"] = "Stereo",
        ["第 {0} 帧"] = "Frame {0}",
        ["{0} × {1} 像素"] = "{0} × {1} px",
        ["  · {0:0.00} 秒"] = "  · {0:0.00} s",
        ["预览位置  {0:0.000} / {1:0.000} 秒"] = "Preview position  {0:0.000} / {1:0.000} s",
        ["可搜索字段；关闭“移除全部”后可编辑元数据。"] = "Fields are searchable. Turn off “Remove all” to edit metadata.",
        ["共 {0} 页；调整列表或输入页码顺序。"] = "{0} pages. Rearrange the list or type a page order.",
        ["此图片包含多个图像帧。仅导出当前帧，原始文件保留。"] = "This image has several frames. Only the current frame is exported; the original is kept.",
        ["调整参数后保存；新文件保存在原目录。"] = "Adjust the settings, then save. The new file goes next to the original.",
        ["预览不可用："] = "Preview unavailable: ",
        ["。仍可填写参数。"] = ". You can still fill in the settings.",
        ["请先在预览上选择覆盖区域。"] = "Select an area on the preview first.",
        ["请先在波形上选择蜂鸣时段。"] = "Select a range on the waveform first.",
        ["至少需要选择一个文件"] = "Select at least one file",
        ["至少需要保留一页。"] = "Keep at least one page.",
        ["更新效果中…"] = "Updating preview…",
        ["正在生成预览"] = "Creating preview",
        ["预览已更新；保存后生成新文件。"] = "Preview updated. Save to create the new file.",
        ["预览："] = "Preview: ",
        ["请切换到原文件，再选择画面或音频范围。"] = "Switch to the original before selecting an area or audio range.",
        ["{0:0.000}–{1:0.000} 秒"] = "{0:0.000}–{1:0.000} s",
        ["已添加 {0} 个蜂鸣时段。"] = "{0} bleep range(s) added.",
        ["区域 {0} · {1} × {2} · {3}"] = "Area {0} · {1} × {2} · {3}",
        ["已添加 {0} 个覆盖区域。"] = "{0} area(s) added.",
        ["正在保存新文件"] = "Saving new file",
        ["处理期间可取消；原文件保留。"] = "You can cancel while it runs; the original is kept.",
        ["已保存 {0} 项：{1}"] = "Saved {0}: {1}",
        ["成功 {0} 项，失败 {1} 项：{2}"] = "{0} succeeded, {1} failed: {2}",
        ["处理已取消，可调整参数后重新保存。"] = "Cancelled. Adjust the settings and save again.",
        ["保存未完成："] = "Save not completed: ",
        ["正在定位视频帧"] = "Finding the video frame",
        ["逐帧："] = "Frame step: ",
        ["正在准备处理效果"] = "Preparing the preview",
        ["正在准备兼容播放"] = "Preparing playback",
    };
}
